#!/bin/bash

for file in "$HOME/.shortcuts/"*; do
[ -f "$file" ] || continue
filename="$(basename "$file")"
target_file=$(find "$HOME/Desktop" -type f -name "$filename.lnk")
adres=$(strings "$target_file" | grep -o -m 1 '[A-Za-z]:\\.*\.exe' | sed 's|\\|/|g')
adres="${adres:2}"
word=$(strings "$target_file" | grep -o -m 1 '[A-Za-z]:\\.*\.exe')
disk_letter=$(echo "$word" | cut -d ':' -f 1)
    if [ "$disk_letter" == "D" ]; then
        new_path="$HOME/storage/downloads/$adres"
        if [ ! -f "$new_path" ]; then
            if [ -f "$target_file" ]; then
                rm "$target_file"
            fi
        fi
elif [ "$disk_letter" == "Z" ]; then
        new_path="/data/data/com.termux/files/$adres"
        if [ ! -f "$new_path" ]; then
            if [ -f "$target_file" ]; then
                rm "$target_file"
            fi
        fi
elif [ "$disk_letter" == "C" ]; then
    ADRES_C=$(sed -n '5p' "$file" | awk '{gsub(/^.{9}/,""); gsub(/.$/,"")}1')
    vers_box=$(sed -n '217p' "$file" | cut -c 8-)
    if [ -d "$PREFIX/glibc-x86" ]; then
        WINE_ST="WOW64"
    elif [ -d "$PREFIX/glibc-wow64" ]; then
        WINE_ST="X86"
    fi
    if [ "$vers_box" == "$WINE_ST" ]; then
        new_path="$PREFIX/glibc/$ADRES_C$adres"
    else
        if [ -d "$PREFIX/glibc-wow64" ]; then
            new_path="$PREFIX/glibc-wow64/$ADRES_C$adres"
        else
            new_path="$PREFIX/glibc-x86/$ADRES_C$adres"
        fi
    fi
    if [ ! -f "$new_path" ]; then
        if [ -n "$target_file" ] && [ -f "$target_file" ]; then
            rm "$target_file"
        fi
    fi
fi
done
source "$PREFIX/mobox/settings"  &>/dev/null
.  $PREFIX/mobox/cleaner_links  &>/dev/null
sleep 0.5
folder_path="$HOME/.shortcuts"
mapfile -t file_array < <(find "$folder_path" -maxdepth 1 -type f)
if [ ${#file_array[@]} -gt 0 ]; then
    options=()
    for index in "${!file_array[@]}"; do
        options+=("🎮  $(basename "${file_array[$index]}")" "")
    done
    
    index_gam=$((index+13))
    selection=$(dialog --no-shadow \
    --extra-button \
                --ok-label "Настроить " \
                --extra-label "Запустить" \
                --cancel-label " Cancel " \
                --menu "  Widget для WEG™⚡️Mobox Menu v5.3
─────────────────────────────────────\n
  Индивидуальная настрайка и запуск\n
     приложений в эмуляторе Mobox\n
─────────────────────────────────────\n
       Выберите игру из списка" $index_gam 41 10 "${options[@]}" \
                3>&1 1>&2 2>&3 3>&-)
exit_code=$?
file="${selection:3}"
fire_ek="$folder_path/$file"
case $exit_code in
  0)
    settings_game "$fire_ek" "$HOME/Settings"
    exit
    ;;
  1) 
    exit
    ;;
  3)
    clear
    unset settings
    . "$HOME/.shortcuts/$file"
    exit
    ;;
esac
else
    dialog --no-shadow \
    --msgbox "Список игр пуст. Пожалуйста, создайте\n
 ярлык на рабочем столе WINE, что бы \n
       добавить игру в список" 7 41
fi
