#!/bin/bash

. $PREFIX/glibc/opt/package-manager/token
function wget-git-q {
	wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
	return $?
}
mv $PREFIX/glibc/opt/package-manager/package-manager $PREFIX/glibc/opt/package-manager/package-manager-bak 
wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"
	rm $PREFIX/glibc/opt/package-manager/package-manager-bak
	. $PREFIX/glibc/opt/package-manager/package-manager
sleep 1
termux-fix-shebang "$PREFIX/glibc/opt/scripts/start-tfm"
. $PREFIX/glibc/opt/scripts/mobox_menu