#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Настройки префикса Wine" "" \
	"1" "Удалить префикс" \
	"2" "Изменить режим Wine ESINC"
defitem=$?
case $defitem in
1)
	dialog_yesno "Вы уверены?"
	if [ "$?" = "0" ]; then
		rm -rf $WINEPREFIX
	fi
;;
2)
	if [[ ! "$WINE_PATH" = *"wine-ge-custom-8-25"* ]] || [ ! -e "$WINE_PATH" ]; then
		echo "WINEESYNC отключен, так как выбрана старая версия wine_path."
		echo "Хотите установить (если не установлен) и включить Wine-ge-custom-8-25 автоматически? (Y/n)"
		read i
		if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
			load_package-manager
			if [ "$?" = "1" ]; then
				continue
			fi
			sync-package wine-ge-custom-8-25
			echo "export WINE_PATH=\$PREFIX/glibc/wine-ge-custom-8-25
export WINEPREFIX=\$PREFIX/glibc/wine-ge-custom-8-25/.wine">$PREFIX/glibc/opt/conf/wine_path.conf
		fi
		continue
	fi
	while true; do
	load_configs
	dialog_menu "Настройка WINEESYNC" "\ZbCurrent settings:\Zn
	\Z3WINEESYNC\Z2=\Zn$WINEESYNC
	\Z3WINEESYNC no root mode\Z2=\Zn$WINEESYNC_TERMUX" \
	"1" "Отключить esync" \
	"2" "Включить esync без root прав (ускоряет работу программ)" \
	"3" "Включить esync с наличием root прав (ускоряет работу программ еще быстрее)"
	case $? in
	1) echo "export WINEESYNC=0
export WINEESYNC_TERMUX=0">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	2) echo "export WINEESYNC=1
export WINEESYNC_TERMUX=1">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	3) echo "export WINEESYNC=1
export WINEESYNC_TERMUX=0">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	255) break ;;
	esac
	done
;;
255)
	break
;;
esac
done
