#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Root settings" "" \
	"1" "Закрыть фоновые приложения" \
	"2" "Запустить Termux, Termux X11 и наладчик OOM InputBridge"
defitem=$?
case $defitem in
1)
	chmod 777 $PREFIX/glibc/opt/scripts/close-apps
	sudo bash $PREFIX/glibc/opt/scripts/close-apps
	sleep 3
;;
2)
	chmod 777 $PREFIX/glibc/opt/scripts/termux-adj
	sudo bash $PREFIX/glibc/opt/scripts/termux-adj &
	echo "Теперь запущен OOM регулятор. Пожалуйста, не используйте эту опцию более одного раза! Чтобы остановить ее - принудительно, остановите Termux"
	sleep 4
;;
255)
	break
;;
esac
done
