#!/bin/bash

defitem=1
ADRESS="$HOME/.shortcuts/Mobox WoW64"

while true; do
load_configs
dialog_menu_item $defitem "DXVK settings" "\ZbCurrent settings:
	\Z3$(sed '3q;d' $DXVK_CONFIG_FILE)
	$(sed '4q;d' $DXVK_CONFIG_FILE)
	$(sed '6q;d' $DXVK_CONFIG_FILE)\Zn" \
	"1" "d3d11.maxFeatureLevel" \
	"2" "dxgi.maxFrameRate" \
	"3" "dxgi.syncInterval (vsync)" \
	"4" "Edit config manually" \
	"5" "Reset to default"
defitem=$?
case $defitem in
1)
	dialog_menu "" "" \
"1" "d3d11.maxFeatureLevel = 9_1" \
"2" "d3d11.maxFeatureLevel = 9_2" \
"3" "d3d11.maxFeatureLevel = 9_3" \
"4" "d3d11.maxFeatureLevel = 10_0" \
"5" "d3d11.maxFeatureLevel = 10_1" \
"6" "d3d11.maxFeatureLevel = 11_0" \
"7" "d3d11.maxFeatureLevel = 11_1" \
"8" "d3d11.maxFeatureLevel = 12_0" \
"9" "d3d11.maxFeatureLevel = 12_1"
	case $? in
	1) sed -i '3s/.*/d3d11.maxFeatureLevel = 9_1/' $DXVK_CONFIG_FILE 
	sed -i "30s/.*/DX_VER_WOW=9_1/" "$ADRESS";;
	2) sed -i '3s/.*/d3d11.maxFeatureLevel = 9_2/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=9_2/" "$ADRESS";;
	3) sed -i '3s/.*/d3d11.maxFeatureLevel = 9_3/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=9_3/" "$ADRESS";;
	4) sed -i '3s/.*/d3d11.maxFeatureLevel = 10_0/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=10_0/" "$ADRESS";;
	5) sed -i '3s/.*/d3d11.maxFeatureLevel = 10_1/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=10_1/" "$ADRESS";;
	6) sed -i '3s/.*/d3d11.maxFeatureLevel = 11_0/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=11_0/" "$ADRESS";;
	7) sed -i '3s/.*/d3d11.maxFeatureLevel = 11_1/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=11_1/" "$ADRESS";;
	8) sed -i '3s/.*/d3d11.maxFeatureLevel = 12_0/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=12_0/" "$ADRESS";;
	9) sed -i '3s/.*/d3d11.maxFeatureLevel = 12_1/' $DXVK_CONFIG_FILE
	sed -i "30s/.*/DX_VER_WOW=12_1/" "$ADRESS";;
	esac
;;
2)
	dialog_menu "" "" \
"1" "dxgi.maxFrameRate = 0 (unlimited)" \
"2" "dxgi.maxFrameRate = 15" \
"3" "dxgi.maxFrameRate = 24" \
"4" "dxgi.maxFrameRate = 30" \
"5" "dxgi.maxFrameRate = 40" \
"6" "dxgi.maxFrameRate = 50" \
"7" "dxgi.maxFrameRate = 60" \
"8" "dxgi.maxFrameRate = 90" \
"9" "dxgi.maxFrameRate = 120" \
"10" "dxgi.maxFrameRate = 144"
	case $? in
	1)
		sed -i '4s/.*/dxgi.maxFrameRate = 0/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 0/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=0/" "$ADRESS"
	;;
	2)
		sed -i '4s/.*/dxgi.maxFrameRate = 15/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 15/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=15/" "$ADRESS"
	;;
	3)
		sed -i '4s/.*/dxgi.maxFrameRate = 24/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 24/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=24/" "$ADRESS"
	;;
	4)
		sed -i '4s/.*/dxgi.maxFrameRate = 30/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 30/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=30/" "$ADRESS"
	;;
	5)
		sed -i '4s/.*/dxgi.maxFrameRate = 40/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 40/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=40/" "$ADRESS"
	;;
	6)
		sed -i '4s/.*/dxgi.maxFrameRate = 50/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 50/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=50/" "$ADRESS"
	;;
	7)
		sed -i '4s/.*/dxgi.maxFrameRate = 60/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 60/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=60/" "$ADRESS"
	;;
	8)
		sed -i '4s/.*/dxgi.maxFrameRate = 90/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 90/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=90/" "$ADRESS"
	;;
	9)
		sed -i '4s/.*/dxgi.maxFrameRate = 120/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 120/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=120/" "$ADRESS"
	;;
	10)
		sed -i '4s/.*/dxgi.maxFrameRate = 144/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 144/' $DXVK_CONFIG_FILE
		sed -i "35s/.*/FPS_LIM_WOW=144/" "$ADRESS"
	;;
	esac
;;
3)
	dialog_menu "" "" \
"1" "dxgi.syncInterval = -1 (no effect)" \
"2" "dxgi.syncInterval = 0 (no vsync)" \
"3" "dxgi.syncInterval = 1 (vsync)" \
"4" "dxgi.syncInterval = 2 (50% vsync)"
	case $? in
	1)
		sed -i '6s/.*/dxgi.syncInterval = -1/' $DXVK_CONFIG_FILE
		sed -i '7s/.*/d3d9.presentInterval = -1/' $DXVK_CONFIG_FILE
	;;
	2)
		sed -i '6s/.*/dxgi.syncInterval = 0/' $DXVK_CONFIG_FILE
		sed -i '7s/.*/d3d9.presentInterval = 0/' $DXVK_CONFIG_FILE
	;;
	3)
		sed -i '6s/.*/dxgi.syncInterval = 1/' $DXVK_CONFIG_FILE
		sed -i '7s/.*/d3d9.presentInterval = 1/' $DXVK_CONFIG_FILE
	;;
	4)
		sed -i '6s/.*/dxgi.syncInterval = 2/' $DXVK_CONFIG_FILE
		sed -i '7s/.*/d3d9.presentInterval = 2/' $DXVK_CONFIG_FILE
	;;
	esac
;;
4)
	i=$(dialog_editbox $PREFIX/glibc/opt/dxvk.conf)
	ret=$?
	if [ $ret = 1 ] || [ $ret = 255 ]; then continue; fi
	echo "$i">$PREFIX/glibc/opt/dxvk.conf
;;
5)
	cp $PREFIX/glibc/opt/default-conf/dxvk.conf $PREFIX/glibc/opt
;;
255)
	break
;;
esac
done
