#!/bin/bash

ALIGNED_ATOMICS=$(sed -n "130p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
BIGBLOCK_64=$(sed -n "131p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
BIGBLOCK_86=$(sed -n "132p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
FASTNAN=$(sed -n "133p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
SAFEFLAGS=$(sed -n "134p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
STRONGMEM=$(sed -n "135p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
WAIT=$(sed -n "136p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
X87DOUBLE=$(sed -n "137p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
CALLRET=$(sed -n "138p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')

ALIGNED_ATOMICS_0=$(sed -n "130p" "$CONFIG")
BIGBLOCK_64_0=$(sed -n "131p" "$CONFIG")
BIGBLOCK_86_0=$(sed -n "132p" "$CONFIG")
FASTNAN_0=$(sed -n "133p" "$CONFIG")
SAFEFLAGS_0=$(sed -n "134p" "$CONFIG")
STRONGMEM_0=$(sed -n "135p" "$CONFIG")
WAIT_0=$(sed -n "136p" "$CONFIG")
X87DOUBLE_0=$(sed -n "137p" "$CONFIG")
CALLRET_0=$(sed -n "138p" "$CONFIG")

ALIGNED_ATOMICS_64=$(sed -n "144p" "$CONFIG")
ALIGNED_ATOMICS_86=$(sed -n "145p" "$CONFIG")
BIGBLOCK_64_64=$(sed -n "146p" "$CONFIG")
BIGBLOCK_86_86=$(sed -n "147p" "$CONFIG")
FASTNAN_64=$(sed -n "148p" "$CONFIG")
FASTNAN_86=$(sed -n "149p" "$CONFIG")
SAFEFLAGS_64=$(sed -n "150p" "$CONFIG")
SAFEFLAGS_86=$(sed -n "151p" "$CONFIG")
STRONGMEM_64=$(sed -n "152p" "$CONFIG")
STRONGMEM_86=$(sed -n "153p" "$CONFIG")
WAIT_64=$(sed -n "154p" "$CONFIG")
WAIT_86=$(sed -n "155p" "$CONFIG")
X87DOUBLE_64=$(sed -n "156p" "$CONFIG")
X87DOUBLE_86=$(sed -n "157p" "$CONFIG")
CALLRET_64=$(sed -n "158p" "$CONFIG")
CALLRET_86=$(sed -n "159p" "$CONFIG")
DINAR=$(sed -n '128p' "$CONFIG" | cut -c 3-)

while true; do
    DYNAREC_CHOICE=$(dialog --no-shadow \
    --title "Выберите значение DYNAREC" \
        --inputbox "\n
Введите подходящую конфигурацию DYNAREC\n
для работы $result\n
- комбинация цифр, например, 424, 45\n
- ввести 0 для детальной настройки\n
- ввести 5 для дополнительной информации\n
────────────────────────────────────────\n
После первой цифры все следующие цифры \n
должны быть разные и дублировать их не \n
имеет смысла. Их порядок не влияет на\n
результат.\n
────────────────────────────────────────\n
Первая цифра от 1 до 4\n
Следующие -  от 1 до 5" 22 44 $DINAR 2>&1 >/dev/tty)
    if [ $? -ne 0 ]; then
       break
    fi
        set_dynarec_param() {
        default_dynarec_item=1
        while true; do
            ext=1
dynarec_choice=$(dialog --no-shadow \
--title "Настройки DYNAREC" \
    --default-item "$default_dynarec_item" \
    --menu " \n" \
    18 35 11 \
" DYNAREC_ALIGNED_ATOMICS =" "$ALIGNED_ATOMICS " \
" BOX64_DYNAREC_BIGBLOCK =" "$BIGBLOCK_64 " \
" BOX86_DYNAREC_BIGBLOCK =" "$BIGBLOCK_86 " \
" DYNAREC_FASTNAN =" "$FASTNAN " \
" DYNAREC_SAFEFLAGS =" "$SAFEFLAGS " \
" DYNAREC_STRONGMEM =" "$STRONGMEM " \
" DYNAREC_WAIT =" "$WAIT " \
" DYNAREC_X87DOUBLE =" "$X87DOUBLE " \
" DYNAREC_CALLRET =" "$CALLRET " \
" Сброс к значению по умолчанию" "" \
" Перейти к цифровым значениям" "" 3>&1 1>&2 2>&3)
        case $? in
            1) 
sed -i "130s/.*/$ALIGNED_ATOMICS_0/" "$CONFIG"
sed -i "144s/.*/$ALIGNED_ATOMICS_64/" "$CONFIG"
sed -i "145s/.*/$ALIGNED_ATOMICS_86/" "$CONFIG"
sed -i "131s/.*/$BIGBLOCK_64_0/" "$CONFIG"
sed -i "146s/.*/$BIGBLOCK_64_64/" "$CONFIG"
sed -i "132s/.*/$BIGBLOCK_86_0/" "$CONFIG"
sed -i "147s/.*/$BIGBLOCK_86_86/" "$CONFIG"
sed -i "133s/.*/$FASTNAN_0/" "$CONFIG"
sed -i "148s/.*/$FASTNAN_64/" "$CONFIG"
sed -i "149s/.*/$FASTNAN_86/" "$CONFIG"
sed -i "134s/.*/$SAFEFLAGS_0/" "$CONFIG"
sed -i "150s/.*/$SAFEFLAGS_64/" "$CONFIG"
sed -i "151s/.*/$SAFEFLAGS_86/" "$CONFIG"
sed -i "135s/.*/$STRONGMEM_0/" "$CONFIG"

sed -i "152s/.*/$STRONGMEM_64/" "$CONFIG"
sed -i "153s/.*/$STRONGMEM_86/" "$CONFIG"
sed -i "136s/.*/$WAIT_0/" "$CONFIG"
sed -i "154s/.*/$WAIT_64/" "$CONFIG"
sed -i "155s/.*/$WAIT_86/" "$CONFIG"
sed -i "137s/.*/$X87DOUBLE_0/" "$CONFIG"
sed -i "156s/.*/$X87DOUBLE_64/" "$CONFIG"
sed -i "157s/.*/$X87DOUBLE_86/" "$CONFIG"
sed -i "138s/.*/$CALLRET_0/" "$CONFIG"
sed -i "158s/.*/$CALLRET_64/" "$CONFIG"
sed -i "159s/.*/$CALLRET_86/" "$CONFIG"
          save_settings
            break 
            ;;
        esac
            default_dynarec_item=$dynarec_choice
        case "$dynarec_choice" in
" DYNAREC_ALIGNED_ATOMICS =")
                if [ "$ALIGNED_ATOMICS" = "0" ]; then
                    ALIGNED_ATOMICS="1"
                elif [ "$ALIGNED_ATOMICS" = "1" ]; then
                    ALIGNED_ATOMICS="-"
                elif [ "$ALIGNED_ATOMICS" = "-" ]; then
                    ALIGNED_ATOMICS="0"
                fi ;;
" BOX64_DYNAREC_BIGBLOCK =")
                if [ "$BIGBLOCK_64" = "0" ]; then
                    BIGBLOCK_64="1"
                elif [ "$BIGBLOCK_64" = "1" ]; then
                    BIGBLOCK_64="2"
                elif [ "$BIGBLOCK_64" = "2" ]; then
                    BIGBLOCK_64="-"
                elif [ "$BIGBLOCK_64" = "-" ]; then
                    BIGBLOCK_64="0"
                fi ;;
" BOX86_DYNAREC_BIGBLOCK =")
                if [ "$BIGBLOCK_86" = "0" ]; then
                    BIGBLOCK_86="1"
                elif [ "$BIGBLOCK_86" = "1" ]; then
                    BIGBLOCK_86="2"
                elif [ "$BIGBLOCK_86" = "2" ]; then
                    BIGBLOCK_86="-"
                elif [ "$BIGBLOCK_86" = "-" ]; then
                    BIGBLOCK_86="0"
                fi ;;
" DYNAREC_FASTNAN =")
                if [ "$FASTNAN" = "0" ]; then
                    FASTNAN="1"
                elif [ "$FASTNAN" = "1" ]; then
                    FASTNAN="-"
                elif [ "$FASTNAN" = "-" ]; then
                    FASTNAN="0"
                fi ;;
" DYNAREC_SAFEFLAGS =")
                if [ "$SAFEFLAGS" = "0" ]; then
                    SAFEFLAGS="1"
                elif [ "$SAFEFLAGS" = "1" ]; then
                    SAFEFLAGS="2"
                elif [ "$SAFEFLAGS" = "2" ]; then
                    SAFEFLAGS="-"
                elif [ "$SAFEFLAGS" = "-" ]; then
                    SAFEFLAGS="0"
                fi ;;
" DYNAREC_STRONGMEM =")
                if [ "$STRONGMEM" = "0" ]; then
                    STRONGMEM="1"
                elif [ "$STRONGMEM" = "1" ]; then
                    STRONGMEM="2"
                elif [ "$STRONGMEM" = "2" ]; then
                    STRONGMEM="3"
                elif [ "$STRONGMEM" = "3" ]; then
                    STRONGMEM="-"
                elif [ "$STRONGMEM" = "-" ]; then
                    STRONGMEM="0"
                fi ;;
" DYNAREC_WAIT =")
                if [ "$WAIT" = "0" ]; then
                    WAIT="1"
                elif [ "$WAIT" = "1" ]; then
                    WAIT="-"
                elif [ "$WAIT" = "-" ]; then
                    WAIT="0"
                fi ;;
" DYNAREC_X87DOUBLE =")
                if [ "$X87DOUBLE" = "0" ]; then
                    X87DOUBLE="1"
                elif [ "$X87DOUBLE" = "1" ]; then
                    X87DOUBLE="-"
                elif [ "$X87DOUBLE" = "-" ]; then
                    X87DOUBLE="0"
                fi ;;
" DYNAREC_CALLRET =")
                if [ "$CALLRET" = "0" ]; then
                    CALLRET="1"
                elif [ "$CALLRET" = "1" ]; then
                    CALLRET="-"
                elif [ "$CALLRET" = "-" ]; then
                    CALLRET="0"
                fi ;;
" Сброс к значению по умолчанию")
                ALIGNED_ATOMICS=-
                BIGBLOCK_64=2
                BIGBLOCK_86=0
                FASTNAN=-
                SAFEFLAGS=2
                STRONGMEM=-
                WAIT=-
                X87DOUBLE=1
                CALLRET=0
                ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=-"
                ALIGNED_ATOMICS_86="echo 'unset BOX86_DYNAREC_ALIGNED_ATOMICS'"
                ALIGNED_ATOMICS_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
                BIGBLOCK_64_0="BIGBLOCK_64=2"
                BIGBLOCK_86_0="BIGBLOCK_86=0"
                BIGBLOCK_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
                BIGBLOCK_86_86="echo 'export BOX86_DYNAREC_BIGBLOCK=0'"
                FASTNAN_0="FASTNAN=-"
                FASTNAN_86="echo 'unset BOX86_DYNAREC_FASTNAN'"
                FASTNAN_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
                SAFEFLAGS_0="SAFEFLAGS=2"
                SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=2'"
                SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
                STRONGMEM_0="STRONGMEM=-"
                STRONGMEM_86="echo 'unset BOX86_DYNAREC_STRONGMEM'"
                STRONGMEM_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
                WAIT_0="WAIT=-"
                WAIT_86="echo 'unset BOX86_DYNAREC_WAIT'"
                WAIT_64="echo 'unset BOX64_DYNAREC_WAIT'"
                X87DOUBLE_0="X87DOUBLE=1"
                X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=1'"
                X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
                CALLRET_0="CALLRET=0"
                CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
                CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
                    ;;
" Перейти к цифровым значениям") 
                    ext=0
                    return
                ;;
            esac
            case ${ALIGNED_ATOMICS} in
                0)
                ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=0"
                ALIGNED_ATOMICS_86="echo 'export BOX86_DYNAREC_ALIGNED_ATOMICS=0'"
                ALIGNED_ATOMICS_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=0'"
                ;;
                1)
                ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=1"
                ALIGNED_ATOMICS_86="echo 'export BOX86_DYNAREC_ALIGNED_ATOMICS=1'"
                ALIGNED_ATOMICS_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=1'"
                ;;
                -)
                ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=-"
                ALIGNED_ATOMICS_86="echo 'unset BOX86_DYNAREC_ALIGNED_ATOMICS'"
                ALIGNED_ATOMICS_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
                ;;       
            esac
            case ${BIGBLOCK_64} in
                0)
                BIGBLOCK_64_0="BIGBLOCK_64=0"
                BIGBLOCK_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=0'"
                ;;
                1)
                BIGBLOCK_64_0="BIGBLOCK_64=1"
                BIGBLOCK_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=1'"
                ;;
                2)
                BIGBLOCK_64_0="BIGBLOCK_64=2"
                BIGBLOCK_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
                ;;
                -)
                BIGBLOCK_64_0="BIGBLOCK_64=-"
                BIGBLOCK_64_64="echo 'unset BOX64_DYNAREC_BIGBLOCK'"
                ;;       
            esac
            case ${BIGBLOCK_86} in
                0)
                BIGBLOCK_86_0="BIGBLOCK_86=0"
                BIGBLOCK_86_86="echo 'export BOX86_DYNAREC_BIGBLOCK=0'"
                ;;
                1)
                BIGBLOCK_86_0="BIGBLOCK_86=1"
                BIGBLOCK_86_86="echo 'export BOX86_DYNAREC_BIGBLOCK=1'"
                ;;
                2)
                BIGBLOCK_86_0="BIGBLOCK_86=2"
                BIGBLOCK_86_86="echo 'export BOX86_DYNAREC_BIGBLOCK=2'"
                ;;
                -)
                BIGBLOCK_86_0="BIGBLOCK_86=-"
                BIGBLOCK_86_86="echo 'unset BOX86_DYNAREC_BIGBLOCK'"
                ;;       
            esac
            case ${FASTNAN} in
                0)
                FASTNAN_0="FASTNAN=0"
                FASTNAN_86="echo 'export BOX86_DYNAREC_FASTNAN=0'"
                FASTNAN_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
                ;;
                1)
                FASTNAN_0="FASTNAN=1"
                FASTNAN_86="echo 'export BOX86_DYNAREC_FASTNAN=1'"
                FASTNAN_64="echo 'export BOX64_DYNAREC_FASTNAN=1'"
                ;;
                -)
                FASTNAN_0="FASTNAN=-"
                FASTNAN_86="echo 'unset BOX86_DYNAREC_FASTNAN'"
                FASTNAN_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
                ;;       
            esac
            case ${SAFEFLAGS} in
                0)
                SAFEFLAGS_0="SAFEFLAGS=0"
                SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=0'"
                SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
                ;;
                1)
                SAFEFLAGS_0="SAFEFLAGS=1"
                SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=1'"
                SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=1'"
                ;;
                2)
                SAFEFLAGS_0="SAFEFLAGS=2"
                SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=2'"
                SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
                ;;
                -)
                SAFEFLAGS_0="SAFEFLAGS=-"
                SAFEFLAGS_86="echo 'unset BOX86_DYNAREC_SAFEFLAGS'"
                SAFEFLAGS_64="echo 'unset BOX64_DYNAREC_SAFEFLAGS'"
                ;;       
            esac
            case ${STRONGMEM} in
                0)
                STRONGMEM_0="STRONGMEM=0"
                STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=0'"
                STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=0'"
                ;;
                1)
                STRONGMEM_0="STRONGMEM=1"
                STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=1'"
                STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
                ;;
                2)
                STRONGMEM_0="STRONGMEM=2"
                STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=2'"
                STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=2'"
                ;;
                3)
                STRONGMEM_0="STRONGMEM=3"
                STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=3'"
                STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=3'"
                ;;
                -)
                STRONGMEM_0="STRONGMEM=-"
                STRONGMEM_86="echo 'unset BOX86_DYNAREC_STRONGMEM'"
                STRONGMEM_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
                ;;       
            esac
            case ${WAIT} in
                0)
                WAIT_0="WAIT=0"
                WAIT_86="echo 'export BOX86_DYNAREC_WAIT=0'"
                WAIT_64="echo 'export BOX64_DYNAREC_WAIT=0'"
                ;;
                1)
                WAIT_0="WAIT=1"
                WAIT_86="echo 'export BOX86_DYNAREC_WAIT=1'"
                WAIT_64="echo 'export BOX64_DYNAREC_WAIT=1'"
                ;;
                -)
                WAIT_0="WAIT=-"
                WAIT_86="echo 'unset BOX86_DYNAREC_WAIT'"
                WAIT_64="echo 'unset BOX64_DYNAREC_WAIT'"
                ;;       
            esac
            case ${X87DOUBLE} in
                0)
                X87DOUBLE_0="X87DOUBLE=0"
                X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=0'"
                X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=0'"
                ;;
                1)
                X87DOUBLE_0="X87DOUBLE=1"
                X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=1'"
                X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
                ;;
                -)
                X87DOUBLE_0="X87DOUBLE=-"
                X87DOUBLE_86="echo 'unset BOX86_DYNAREC_X87DOUBLE'"
                X87DOUBLE_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
                ;;       
            esac
            case ${CALLRET} in
                0)
                CALLRET_0="CALLRET=0"
                CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
                CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
                ;;
                1)
                CALLRET_0="CALLRET=1"
                CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=1'"
                CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=1'"
                ;;
                -)
                CALLRET_0="CALLRET=-"
                CALLRET_86="echo 'unset BOX86_DYNAREC_CALLRET'"
                CALLRET_64="echo 'unset BOX64_DYNAREC_CALLRET'"
                ;;       
            esac

        done
        }
set_dynarec() {
FIRST_CHAR=${DYNAREC_CHOICE:0:1}
if [[ "$FIRST_CHAR" =~ ^[1-4]$ ]]; then
sed -i "128s/.*/d=$DYNAREC_CHOICE/" "$CONFIG"
    DYNAREC_86=$DYNAREC_CHOICE
sed -i "127s/.*/DYNAREC_86=$DYNAREC_86/" "$CONFIG"

    if [ $FIRST_CHAR = "1" ]; then
        ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=0"
        ALIGNED_ATOMICS="0"
        ALIGNED_ATOMICS_86="echo 'export BOX86_DYNAREC_ALIGNED_ATOMICS=0'"
        ALIGNED_ATOMICS_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=0'"
        FASTNAN_0="FASTNAN=0"
        FASTNAN="0"
        FASTNAN_86="echo 'export BOX86_DYNAREC_FASTNAN=0'"
        FASTNAN_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
        SAFEFLAGS_0="SAFEFLAGS=2"
        SAFEFLAGS="2"
        SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=2'"
        SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
        STRONGMEM_0="STRONGMEM=3"
        STRONGMEM="3"
        STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=3'"
        STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=3'"
        WAIT_0="WAIT=1"
        WAIT="1"
        WAIT_86="echo 'export BOX86_DYNAREC_WAIT=1'"
        WAIT_64="echo 'export BOX64_DYNAREC_WAIT=1'"
        X87DOUBLE_0="X87DOUBLE=1"
        X87DOUBLE="1"
        X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=1'"
        X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
        CALLRET_0="CALLRET=0"
        CALLRET="0"
        CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
        CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
    elif [ $FIRST_CHAR = "2" ]; then
        ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=-"
        ALIGNED_ATOMICS="-"
        ALIGNED_ATOMICS_86="echo 'unset BOX86_DYNAREC_ALIGNED_ATOMICS'"
        ALIGNED_ATOMICS_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
        FASTNAN_0="FASTNAN=0"
        FASTNAN="0"
        FASTNAN_86="echo 'export BOX86_DYNAREC_FASTNAN=0'"
        FASTNAN_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
        SAFEFLAGS_0="SAFEFLAGS=2"
        SAFEFLAGS="2"
        SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=2'"
        SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
        STRONGMEM_0="STRONGMEM=1"
        STRONGMEM="1"
        STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=1'"
        STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
        WAIT_0="WAIT=-"
        WAIT="-"
        WAIT_86="echo 'unset BOX86_DYNAREC_WAIT'"
        WAIT_64="echo 'unset BOX64_DYNAREC_WAIT'"
        X87DOUBLE_0="X87DOUBLE=1"
        X87DOUBLE="1"
        X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=1'"
        X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
        CALLRET_0="CALLRET=0"
        CALLRET="0"
        CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
        CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
    elif [ $FIRST_CHAR = "3" ]; then
        ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=-"
        ALIGNED_ATOMICS="-"
        ALIGNED_ATOMICS_86="echo 'unset BOX86_DYNAREC_ALIGNED_ATOMICS'"
        ALIGNED_ATOMICS_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
        FASTNAN_0="FASTNAN=-"
        FASTNAN="-"
        FASTNAN_86="echo 'unset BOX86_DYNAREC_FASTNAN'"
        FASTNAN_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
        SAFEFLAGS_0="SAFEFLAGS=-"
        SAFEFLAGS="-"
        SAFEFLAGS_86="echo 'unset BOX86_DYNAREC_SAFEFLAGS'"
        SAFEFLAGS_64="echo 'unset BOX64_DYNAREC_SAFEFLAGS'"
        STRONGMEM_0="STRONGMEM=-"
        STRONGMEM="-"
        STRONGMEM_86="echo 'unset BOX86_DYNAREC_STRONGMEM'"
        STRONGMEM_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
        WAIT_0="WAIT=-"
        WAIT="-"
        WAIT_86="echo 'unset BOX86_DYNAREC_WAIT'"
        WAIT_64="echo 'unset BOX64_DYNAREC_WAIT'"
        X87DOUBLE_0="X87DOUBLE=-"
        X87DOUBLE="-"
        X87DOUBLE_86="echo 'unset BOX86_DYNAREC_X87DOUBLE'"
        X87DOUBLE_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
        CALLRET_0="CALLRET=0"
        CALLRET="0"
        CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
        CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
    elif [ $FIRST_CHAR = "4" ]; then
        ALIGNED_ATOMICS_0="ALIGNED_ATOMICS=-"
        ALIGNED_ATOMICS="-"
        ALIGNED_ATOMICS_86="echo 'unset BOX86_DYNAREC_ALIGNED_ATOMICS'"
        ALIGNED_ATOMICS_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
        FASTNAN_0="FASTNAN=-"
        FASTNAN="-"
        FASTNAN_86="echo 'unset BOX86_DYNAREC_FASTNAN'"
        FASTNAN_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
        SAFEFLAGS_0="SAFEFLAGS=0"
        SAFEFLAGS="0"
        SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=0'"
        SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
        STRONGMEM_0="STRONGMEM=-"
        STRONGMEM="-"
        STRONGMEM_86="echo 'unset BOX86_DYNAREC_STRONGMEM'"
        STRONGMEM_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
        WAIT_0="WAIT=-"
        WAIT="-"
        WAIT_86="echo 'unset BOX86_DYNAREC_WAIT'"
        WAIT_64="echo 'unset BOX64_DYNAREC_WAIT'"
        X87DOUBLE_0="X87DOUBLE=-"
        X87DOUBLE="-"
        X87DOUBLE_86="echo 'unset BOX86_DYNAREC_X87DOUBLE'"
        X87DOUBLE_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
        CALLRET_0="CALLRET=0"
        CALLRET="0"
        CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=0'"
        CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
        fi
        
for (( j=1; j<${#DYNAREC_CHOICE}; j++ )); do
    case ${DYNAREC_CHOICE:$j:1} in
        1)
        	FASTNAN_0="FASTNAN=0"
            FASTNAN="0"
            FASTNAN_86="echo 'export BOX86_DYNAREC_FASTNAN=0'"
            FASTNAN_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
        ;;
        2)
        	X87DOUBLE_0="X87DOUBLE=1"
            X87DOUBLE="1"
            X87DOUBLE_86="echo 'export BOX86_DYNAREC_X87DOUBLE=1'"
            X87DOUBLE_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
        ;;
        3)
            STRONGMEM_0="STRONGMEM=1"
            STRONGMEM="1"
            STRONGMEM_86="echo 'export BOX86_DYNAREC_STRONGMEM=1'"
            STRONGMEM_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
        ;;
        4)
            SAFEFLAGS_0="SAFEFLAGS=2"
            SAFEFLAGS="2"
            SAFEFLAGS_86="echo 'export BOX86_DYNAREC_SAFEFLAGS=2'"
            SAFEFLAGS_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
        ;;
        5)
            CALLRET_0="CALLRET=1"
            CALLRET="1"
            CALLRET_86="echo 'export BOX86_DYNAREC_CALLRET=1'"
            CALLRET_64="echo 'export BOX64_DYNAREC_CALLRET=1'"
        ;;
        esac
    done
else
    return
fi
        BIGBLOCK_64="2"
        BIGBLOCK_64_0="BIGBLOCK_64=2"
        BIGBLOCK_86="0"
        BIGBLOCK_86_0="BIGBLOCK_86=0"
        BIGBLOCK_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
        BIGBLOCK_86_86="echo 'export BOX86_DYNAREC_BIGBLOCK=0'"
sed -i "130s/.*/$ALIGNED_ATOMICS_0/" "$CONFIG"
sed -i "131s/.*/$BIGBLOCK_64_0/" "$CONFIG"
sed -i "132s/.*/$BIGBLOCK_86_0/" "$CONFIG"
sed -i "133s/.*/$FASTNAN_0/" "$CONFIG"
sed -i "134s/.*/$SAFEFLAGS_0/" "$CONFIG"
sed -i "135s/.*/$STRONGMEM_0/" "$CONFIG"
sed -i "136s/.*/$WAIT_0/" "$CONFIG"
sed -i "137s/.*/$X87DOUBLE_0/" "$CONFIG"
sed -i "138s/.*/$CALLRET_0/" "$CONFIG"
sed -i "144s/.*/$ALIGNED_ATOMICS_64/" "$CONFIG"
sed -i "145s/.*/$ALIGNED_ATOMICS_86/" "$CONFIG"
sed -i "146s/.*/$BIGBLOCK_64_64/" "$CONFIG"
sed -i "147s/.*/$BIGBLOCK_86_86/" "$CONFIG"
sed -i "148s/.*/$FASTNAN_64/" "$CONFIG"
sed -i "149s/.*/$FASTNAN_86/" "$CONFIG"
sed -i "150s/.*/$SAFEFLAGS_64/" "$CONFIG"
sed -i "151s/.*/$SAFEFLAGS_86/" "$CONFIG"
sed -i "152s/.*/$STRONGMEM_64/" "$CONFIG"
sed -i "153s/.*/$STRONGMEM_86/" "$CONFIG"
sed -i "154s/.*/$WAIT_64/" "$CONFIG"
sed -i "155s/.*/$WAIT_86/" "$CONFIG"
sed -i "156s/.*/$X87DOUBLE_64/" "$CONFIG"
sed -i "157s/.*/$X87DOUBLE_86/" "$CONFIG"
sed -i "158s/.*/$CALLRET_64/" "$CONFIG"
sed -i "159s/.*/$CALLRET_86/" "$CONFIG"
save_settings
}
if [[ "$DYNAREC_CHOICE" =~ ^[0-9]+$ ]]; then
    if [ "$DYNAREC_CHOICE" = "5" ]; then
    dialog --no-shadow \
    --msgbox "💡 Информация\n\n
Список основных предустановок:\n
1 - максимальная совместимость (медленная)\n
2 - по умолчанию + совместимость\n
3 - по умолчанию (SAFEFLAGS=1)\n
4 - производительный (SAFEFLAGS=0)\n\n
Список дополнительных предустановок:\n
1 - FASTNAN=0  оптимизирует проверку NaN\n
2 - X87DOUBLE=1  улучшает оптимизацию\n
3 - STRONGMEM=1  надежнее работает игра,\n
    но замедляет ее\n
4 - SAFEFLAGS=2  точность эмуляции\n
    процессора (замедляет работу программ)\n
5 - CALLRET=1  улучшает производительность\n\n
Например: 12345\n
1 - основная предустановка\n
2,3,4,5 - дополнительные предустановки" 24 46
    fi
    if [ "$DYNAREC_CHOICE" -gt 0 ] && [ "$DYNAREC_CHOICE" -ne 5 ]; then
        set_dynarec
        break
    elif [ "$DYNAREC_CHOICE" -ne 5 ]; then
        set_dynarec_param
        if [ $ext = "1" ] ; then
DYNAREC_86="$ALIGNED_ATOMICS,$BIGBLOCK_64,$BIGBLOCK_86,$FASTNAN,$SAFEFLAGS,$STRONGMEM,$WAIT,$X87DOUBLE,$CALLRET"
sed -i "127s/.*/DYNAREC_86=$DYNAREC_86/" "$CONFIG"
sed -i "130s/.*/$ALIGNED_ATOMICS_0/" "$CONFIG"
sed -i "131s/.*/$BIGBLOCK_64_0/" "$CONFIG"
sed -i "132s/.*/$BIGBLOCK_86_0/" "$CONFIG"
sed -i "133s/.*/$FASTNAN_0/" "$CONFIG"
sed -i "134s/.*/$SAFEFLAGS_0/" "$CONFIG"
sed -i "135s/.*/$STRONGMEM_0/" "$CONFIG"
sed -i "136s/.*/$WAIT_0/" "$CONFIG"
sed -i "137s/.*/$X87DOUBLE_0/" "$CONFIG"
sed -i "138s/.*/$CALLRET_0/" "$CONFIG"
sed -i "128s/.*/d=0/" "$CONFIG"
sed -i "144s/.*/$ALIGNED_ATOMICS_64/" "$CONFIG"
sed -i "145s/.*/$ALIGNED_ATOMICS_86/" "$CONFIG"
sed -i "146s/.*/$BIGBLOCK_64_64/" "$CONFIG"
sed -i "147s/.*/$BIGBLOCK_86_86/" "$CONFIG"
sed -i "148s/.*/$FASTNAN_64/" "$CONFIG"
sed -i "149s/.*/$FASTNAN_86/" "$CONFIG"
sed -i "150s/.*/$SAFEFLAGS_64/" "$CONFIG"
sed -i "151s/.*/$SAFEFLAGS_86/" "$CONFIG"
sed -i "152s/.*/$STRONGMEM_64/" "$CONFIG"
sed -i "153s/.*/$STRONGMEM_86/" "$CONFIG"
sed -i "154s/.*/$WAIT_64/" "$CONFIG"
sed -i "155s/.*/$WAIT_86/" "$CONFIG"
sed -i "156s/.*/$X87DOUBLE_64/" "$CONFIG"
sed -i "157s/.*/$X87DOUBLE_86/" "$CONFIG"
sed -i "158s/.*/$CALLRET_64/" "$CONFIG"
sed -i "159s/.*/$CALLRET_86/" "$CONFIG"
save_settings
            return
        fi
    fi
fi
done