#!/bin/bash

ATOMICS_WOW=$(sed -n "49p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
BIGBLOCK_WOW=$(sed -n "50p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
FASTNAN_WOW=$(sed -n "51p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
SAFEFLAGS_WOW=$(sed -n "52p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
STRONGMEM_WOW=$(sed -n "53p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
WAIT_WOW=$(sed -n "54p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
X87DOUBLE_WOW=$(sed -n "55p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
CALLRET_WOW=$(sed -n "56p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
FASTROUND_WOW=$(sed -n "57p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')
IGNOREINT3_WOW=$(sed -n "58p" "$CONFIG" | awk '{print substr($0, length($0), 1)}')

ATOMICS_WOW_0=$(sed -n "49p" "$CONFIG")
BIGBLOCK_WOW_0=$(sed -n "50p" "$CONFIG")
FASTNAN_WOW_0=$(sed -n "51p" "$CONFIG")
SAFEFLAGS_WOW_0=$(sed -n "52p" "$CONFIG")
STRONGMEM_WOW_0=$(sed -n "53p" "$CONFIG")
WAIT_WOW_0=$(sed -n "54p" "$CONFIG")
X87DOUBLE_WOW_0=$(sed -n "55p" "$CONFIG")
CALLRET_WOW_0=$(sed -n "56p" "$CONFIG")
FASTROUND_WOW_0=$(sed -n "57p" "$CONFIG")
IGNOREINT3_WOW_0=$(sed -n "58p" "$CONFIG")

ATOMICS_WOW_64=$(sed -n "64p" "$CONFIG")
BIGBLOCK_WOW_64=$(sed -n "65p" "$CONFIG")
FASTNAN_WOW_64=$(sed -n "66p" "$CONFIG")
SAFEFLAGS_WOW_64=$(sed -n "67p" "$CONFIG")
STRONGMEM_WOW_64=$(sed -n "68p" "$CONFIG")
WAIT_WOW_64=$(sed -n "69p" "$CONFIG")
X87DOUBLE_WOW_64=$(sed -n "70p" "$CONFIG")
CALLRET_WOW_64=$(sed -n "71p" "$CONFIG")
FASTROUND_WOW_64=$(sed -n "72p" "$CONFIG")
IGNOREINT3_WOW_64=$(sed -n "73p" "$CONFIG")
DINAR=$(sed -n '48p' "$CONFIG" | cut -c 3-)

while true; do
    DYNAREC_CHOICE=$(dialog --no-shadow \
    --title "Выберите значение DYNAREC" \
        --inputbox "\n
Введите подходящую конфигурацию DYNAREC\n
для работы $result\n
- комбинация цифр, например, 424, 45\n
- ввести 0 для детальной настройки\n
- ввести 5 для дополнительной информации\n
────────────────────────────────────────\n
После первой цифры все следующие цифры \n
должны быть разные и дублировать их не \n
имеет смысла. Их порядок не влияет на\n
результат.\n
────────────────────────────────────────\n
Первая цифра от 1 до 4\n
Следующие -  от 1 до 9" 22 44 $DINAR 2>&1 >/dev/tty)
    if [ $? -ne 0 ]; then
       break
    fi
        set_dynarec_param() {
        default_dynarec_item=1
        while true; do
            ext=1
echo "export DYNAREC_SETTINGS_SCRIPT=1">$PREFIX/glibc/opt/conf/dynarec_preset.conf
dynarec_choice=$(dialog --no-shadow \
--title "Настройки DYNAREC" \
    --default-item "$default_dynarec_item" \
    --menu " \n" \
    19 35 11 \
" DYNAREC_ALIGNED_ATOMICS =" "$ATOMICS_WOW " \
" BOX64_DYNAREC_BIGBLOCK =" "$BIGBLOCK_WOW " \
" DYNAREC_FASTNAN =" "$FASTNAN_WOW " \
" DYNAREC_SAFEFLAGS =" "$SAFEFLAGS_WOW " \
" DYNAREC_STRONGMEM =" "$STRONGMEM_WOW " \
" DYNAREC_WAIT =" "$WAIT_WOW " \
" DYNAREC_X87DOUBLE =" "$X87DOUBLE_WOW " \
" DYNAREC_CALLRET =" "$CALLRET_WOW " \
" DYNAREC_FASTROUND =" "$FASTROUND_WOW " \
" IGNOREINT3 =" "$IGNOREINT3_WOW " \
" Сброс к значению по умолчанию" "" \
" Перейти к цифровым значениям" "" 3>&1 1>&2 2>&3)
        case $? in
            1) 
sed -i "49s/.*/$ATOMICS_WOW_0/" "$CONFIG"
sed -i "50s/.*/$BIGBLOCK_WOW_0/" "$CONFIG"
sed -i "51s/.*/$FASTNAN_WOW_0/" "$CONFIG"
sed -i "52s/.*/$SAFEFLAGS_WOW_0/" "$CONFIG"
sed -i "53s/.*/$STRONGMEM_WOW_0/" "$CONFIG"
sed -i "54s/.*/$WAIT_WOW_0/" "$CONFIG"
sed -i "55s/.*/$X87DOUBLE_WOW_0/" "$CONFIG"
sed -i "56s/.*/$CALLRET_WOW_0/" "$CONFIG"
sed -i "57s/.*/$FASTROUND_WOW_0/" "$CONFIG"
sed -i "58s/.*/$IGNOREINT3_WOW_0/" "$CONFIG"
sed -i "64s/.*/$ATOMICS_WOW_64/" "$CONFIG"
sed -i "65s/.*/$BIGBLOCK_WOW_64/" "$CONFIG"
sed -i "66s/.*/$FASTNAN_WOW_64/" "$CONFIG"
sed -i "67s/.*/$SAFEFLAGS_WOW_64/" "$CONFIG"
sed -i "68s/.*/$STRONGMEM_WOW_64/" "$CONFIG"
sed -i "69s/.*/$WAIT_WOW_64/" "$CONFIG"
sed -i "70s/.*/$X87DOUBLE_WOW_64/" "$CONFIG"
sed -i "71s/.*/$CALLRET_WOW_64/" "$CONFIG"
sed -i "72s/.*/$FASTROUND_WOW_64/" "$CONFIG"
sed -i "73s/.*/$IGNOREINT3_WOW_64/" "$CONFIG"
            save_settings
echo "${ATOMICS_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
echo "${BIGBLOCK_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
echo "${FASTNAN_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
echo "${SAFEFLAGS_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
echo "${STRONGMEM_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
echo "${WAIT_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/wait.conf
echo "${X87DOUBLE_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
echo "${CALLRET_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/callret.conf
echo "${FASTROUND_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
echo "${IGNOREINT3_WOW_64:6:-1}">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
            break ;;
        esac
            default_dynarec_item=$dynarec_choice
        case "$dynarec_choice" in
" DYNAREC_ALIGNED_ATOMICS =")
               if [ "$ATOMICS_WOW" = "0" ]; then
                    ATOMICS_WOW="1"
                elif [ "$ATOMICS_WOW" = "1" ]; then
                    ATOMICS_WOW="-"
                elif [ "$ATOMICS_WOW" = "-" ]; then
                    ATOMICS_WOW="0"
                fi ;;
" BOX64_DYNAREC_BIGBLOCK =")
                if [ "$BIGBLOCK_WOW" = "0" ]; then
                    BIGBLOCK_WOW="1"
                elif [ "$BIGBLOCK_WOW" = "1" ]; then
                    BIGBLOCK_WOW="2"
                elif [ "$BIGBLOCK_WOW" = "2" ]; then
                    BIGBLOCK_WOW="-"
                elif [ "$BIGBLOCK_WOW" = "-" ]; then
                    BIGBLOCK_WOW="0"
                fi ;;
" DYNAREC_FASTNAN =")
                if [ "$FASTNAN_WOW" = "0" ]; then
                    FASTNAN_WOW="1"
                elif [ "$FASTNAN_WOW" = "1" ]; then
                    FASTNAN_WOW="-"
                elif [ "$FASTNAN_WOW" = "-" ]; then
                    FASTNAN_WOW="0"
                fi ;;
" DYNAREC_SAFEFLAGS =")
                if [ "$SAFEFLAGS_WOW" = "0" ]; then
                    SAFEFLAGS_WOW="1"
                elif [ "$SAFEFLAGS_WOW" = "1" ]; then
                    SAFEFLAGS_WOW="2"
                elif [ "$SAFEFLAGS_WOW" = "2" ]; then
                    SAFEFLAGS_WOW="-"
                elif [ "$SAFEFLAGS_WOW" = "-" ]; then
                    SAFEFLAGS_WOW="0"
                fi ;;
" DYNAREC_STRONGMEM =")
                if [ "$STRONGMEM_WOW" = "0" ]; then
                    STRONGMEM_WOW="1"
                elif [ "$STRONGMEM_WOW" = "1" ]; then
                    STRONGMEM_WOW="2"
                elif [ "$STRONGMEM_WOW" = "2" ]; then
                    STRONGMEM_WOW="3"
                elif [ "$STRONGMEM_WOW" = "3" ]; then
                    STRONGMEM_WOW="-"
                elif [ "$STRONGMEM_WOW" = "-" ]; then
                            STRONGMEM_WOW="0"
                fi ;;
" DYNAREC_WAIT =")
                if [ "$WAIT_WOW" = "0" ]; then
                    WAIT_WOW="1"
                elif [ "$WAIT_WOW" = "1" ]; then
                    WAIT_WOW="-"
                elif [ "$WAIT_WOW" = "-" ]; then
                    WAIT_WOW="0"
                fi ;;
" DYNAREC_X87DOUBLE=")
                if [ "$X87DOUBLE_WOW" = "0" ]; then
                    X87DOUBLE_WOW="1"
                elif [ "$X87DOUBLE_WOW" = "1" ]; then
                    X87DOUBLE_WOW="-"
                elif [ "$X87DOUBLE_WOW" = "-" ]; then
                    X87DOUBLE_WOW="0"
                fi ;;
" DYNAREC_CALLRET =")
                if [ "$CALLRET_WOW" = "0" ]; then
                    CALLRET_WOW="1"
                elif [ "$CALLRET_WOW" = "1" ]; then
                    CALLRET_WOW="-"
                elif [ "$CALLRET_WOW" = "-" ]; then
                    CALLRET_WOW="0"
                fi ;;
" DYNAREC_FASTROUND =")
                if [ "$FASTROUND_WOW" = "0" ]; then
                    FASTROUND_WOW="1"
                elif [ "$FASTROUND_WOW" = "1" ]; then
                    FASTROUND_WOW="-"
                elif [ "$FASTROUND_WOW" = "-" ]; then
                    FASTROUND_WOW="0"
                fi ;;
" IGNOREINT3 =")
                if [ "$IGNOREINT3_WOW" = "0" ]; then
                    IGNOREINT3_WOW="1"
                elif [ "$IGNOREINT3_WOW" = "1" ]; then
                    IGNOREINT3_WOW="-"
                elif [ "$IGNOREINT3_WOW" = "-" ]; then
                    IGNOREINT3_WOW="0"
                fi ;;
" Сброс к значению по умолчанию")
                ATOMICS_WOW=-
                BIGBLOCK_WOW=2
                FASTNAN_WOW=-
                SAFEFLAGS_WOW=2
                STRONGMEM_WOW=-
                WAIT_WOW=-
                X87DOUBLE_WOW=1
                CALLRET_WOW=0
                FASTROUND_WOW=-
                IGNOREINT3_WOW=-
                ATOMICS_WOW_0="ALIGNED_ATOMICS_WOW=-"
                ATOMICS_WOW_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
                BIGBLOCK_WOW_0="BIGBLOCK_64=2"
                BIGBLOCK_WOW_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
                FASTNAN_WOW_0="FASTNAN_WOW=-"
                FASTNAN_WOW_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
                SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=2"
                SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
                STRONGMEM_WOW_0="STRONGMEM_WOW=-"
                STRONGMEM_WOW_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
                WAIT_WOW_0="WAI_WOWT=-"
                WAIT_WOW_64="echo 'unset BOX64_DYNAREC_WAIT'"
                X87DOUBLE_WOW_0="X87DOUBLE_WOW=1"
                X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
                CALLRET_WOW_0="CALLRET_WOW=0"
                CALLRET_WOW_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
                FASTROUND_WOW_0="FASTROUND_WOW"
                FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
                IGNOREINT3_WOW_0="IGNOREINT3_WOW"
                IGNOREINT3_WOW_64="echo 'unset BOX64_DYNAREC_IGNOREINT3'"
                    ;;
" Перейти к цифровым значениям") 
                    ext=0
                    return
                ;;
                esac
                case ${ATOMICS_WOW} in
                0)
                ATOMICS_WOW_0="ATOMICS_WOW=0"
                ATOMICS_WOW_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=0'"
                ;;
                1)
                ATOMICS_WOW_0="ATOMICS_WOW=1"
                ATOMICS_WOW_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=1'"
                ;;
                -)
                ATOMICS_WOW_0="ATOMICS_WOW=-"
                ATOMICS_WOW_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
                ;;       
                esac
                case ${BIGBLOCK_WOW} in
                0)
                BIGBLOCK_WOW_0="BIGBLOCK_WOW=0"
                BIGBLOCK_WOW_64="echo 'export BOX64_DYNAREC_BIGBLOCK=0'"
                ;;
                1)
                BIGBLOCK_WOW_0="BIGBLOCK_WOW=1"
                BIGBLOCK_WOW_64="echo 'export BOX64_DYNAREC_BIGBLOCK=1'"
                ;;
                2)
                BIGBLOCK_WOW_0="BIGBLOCK_WOW=2"
                BIGBLOCK_WOW_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
                ;;
                -)
                BIGBLOCK_WOW_0="BIGBLOCK_WOW=-"
                BIGBLOCK_WOW_64="echo 'unset BOX64_DYNAREC_BIGBLOCK'"
                ;;       
                esac
                case ${FASTNAN_WOW} in
                0)
                FASTNAN_WOW_0="FASTNAN_WOW=0"
                FASTNAN_WOW_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
                ;;
                1)
                FASTNAN_WOW_0="FASTNAN_WOW=1"
                FASTNAN_WOW_64="echo 'export BOX64_DYNAREC_FASTNAN=1'"
                ;;
                -)
                FASTNAN_WOW_0="FASTNAN_WOW=-"
                FASTNAN_WOW_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
                ;;       
                esac
                case ${SAFEFLAGS_WOW} in
                0)
                SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=0"
                SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
                ;;
                1)
                SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=1"
                SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=1'"
                ;;
                2)
                SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=2"
                SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
                ;;
                -)
                SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=-"
                SAFEFLAGS_WOW_64="echo 'unset BOX64_DYNAREC_SAFEFLAGS'"
                ;;       
                esac
                case ${STRONGMEM_WOW} in
                0)
                STRONGMEM_WOW_0="STRONGMEM_WOW=0"
                STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=0'"
                ;;
                1)
                STRONGMEM_WOW_0="STRONGMEM_WOW=1"
                STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
                ;;
                2)
                STRONGMEM_WOW_0="STRONGMEM_WOW=2"
                STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=2'"
                ;;
                3)
                STRONGMEM_WOW_0="STRONGMEM_WOW=3"
                STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=3'"
                ;;
                -)
                STRONGMEM_WOW_0="STRONGMEM_WOW=-"
                STRONGMEM_WOW_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
                ;;       
                esac
                case ${WAIT_WOW} in
                0)
                WAIT_WOW_0="WAIT_WOW=0"
                WAIT_WOW_64="echo 'export BOX64_DYNAREC_WAIT=0'"
                ;;
                1)
                WAIT_WOW_0="WAIT_WOW=1"
                WAIT_WOW_64="echo 'export BOX64_DYNAREC_WAIT=1'"
                ;;
                -)
                WAIT_WOW_0="WAIT_WOW=-"
                WAIT_WOW_64="echo 'unset BOX64_DYNAREC_WAIT'"
                ;;       
                esac
                case ${X87DOUBLE_WOW} in
                0)
                X87DOUBLE_WOW_0="X87DOUBLE_WOW=0"
                X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=0'"
                ;;
                1)
                X87DOUBLE_WOW_0="X87DOUBLE_WOW=1"
                X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
                ;;
                -)
                X87DOUBLE_WOW_0="X87DOUBLE_WOW=-"
                X87DOUBLE_WOW_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
                ;;       
                esac
                case ${CALLRET_WOW} in
                0)
                CALLRET_WOW_0="CALLRET_WOW=0"
                CALLRET_WOW_64="echo 'export BOX64_DYNAREC_CALLRET=0'"
                ;;
                1)
                CALLRET_WOW_0="CALLRET_WOW=1"
                CALLRET_WOW_64="echo 'export BOX64_DYNAREC_CALLRET=1'"
                ;;
                -)
                CALLRET_WOW_0="CALLRET_WOW=-"
                CALLRET_WOW_64="echo 'unset BOX64_DYNAREC_CALLRET'"
                ;;       
                esac
                case ${FASTROUND_WOW} in
                0)
                FASTROUND_WOW_0="FASTROUND_WOW=0"
                FASTROUND_WOW_64="echo 'export BOX64_DYNAREC_FASTROUND=0'"
                ;;
                1)
                FASTROUND_WOW_0="FASTROUND_WOW=1"
                FASTROUND_WOW_64="echo 'export BOX64_DYNAREC_FASTROUND=1'"
                ;;
                -)
                FASTROUND_WOW_0="FASTROUND_WOW=-"
                FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
                ;;       
                esac
                case ${IGNOREINT3_WOW} in
                0)
                IGNOREINT3_WOW_0="IGNOREINT3_WOW=0"
                IGNOREINT3_WOW_64="echo 'export BOX64_IGNOREINT3=0'"
                ;;
                1)
                IGNOREINT3_WOW_0="IGNOREINT3_WOW=1"
                IGNOREINT3_WOW_64="echo 'export BOX64_IGNOREINT3=1'"
                ;;
                -)
                IGNOREINT3_WOW_0="IGNOREINT3_WOW=-"
                IGNOREINT3_WOW_64="echo 'unset BOX64_IGNOREINT3'"
                ;;
                esac
        done
        }
set_dynarec() {
FIRST_CHAR=${DYNAREC_CHOICE:0:1}
if [[ "$FIRST_CHAR" =~ ^[1-4]$ ]]; then
echo "export DYNAREC_SETTINGS_SCRIPT=2
export DYNAREC_CURRENT_PRESET=$DYNAREC_CHOICE">$PREFIX/glibc/opt/conf/dynarec_preset.conf
sed -i "48s/.*/d=$DYNAREC_CHOICE/" "$CONFIG"
    DYNAREC_64=$DYNAREC_CHOICE
    sed -i "47s/.*/DYNAREC_64=$DYNAREC_64/" "$CONFIG"
    if [ $FIRST_CHAR = "1" ]; then
        ATOMICS_WOW_0="ATOMICS_WOW=0"
        ATOMICS_WOW="0"
        ATOMICS_WOW_64="echo 'export BOX64_DYNAREC_ALIGNED_ATOMICS=1'"
echo "export BOX64_DYNAREC_ALIGNED_ATOMICS=0">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
        FASTNAN_WOW_0="FASTNAN_WOW=0"
        FASTNAN_WOW="0"
        FASTNAN_WOW_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
echo "export BOX64_DYNAREC_FASTNAN=0">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
        SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=2"
        SAFEFLAGS_WOW="2"
        SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
        STRONGMEM_WOW_0="STRONGMEM_WOW=3"
        STRONGMEM_WOW="3"
        STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=3'"
echo "export BOX64_DYNAREC_STRONGMEM=3">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        WAIT_WOW_0="WAIT_WOW=1"
        WAIT_WOW="1"
        WAIT_WOW_64="echo 'export BOX64_DYNAREC_WAIT=1'"
echo "export BOX64_DYNAREC_WAIT=1">$PREFIX/glibc/opt/conf/dynarec/wait.conf
        X87DOUBLE_WOW_0="X87DOUBLE_WOW=1"
        X87DOUBLE_WOW="1"
        X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
        CALLRET_WOW_0="CALLRET_WOW=0"
        CALLRET_WOW="0"
        CALLRET_WOW_64="echo 'echo BOX64_DYNAREC_CALLRET=0'"
echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
        FASTROUND_WOW_0="FASTROUND_WOW=-"
        FASTROUND_WOW="-"
        FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynare
        IGNOREINT3_WOW_0="IGNOREINT3_WOW=-"
        IGNOREINT3_WOW="-"
        IGNOREINT3_WOW_64="echo 'unset BOX64_IGNOREINT3'"
echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
    elif [ $FIRST_CHAR = "2" ]; then
        ATOMICS_WOW_0="ATOMICS_WOW=-"
        ATOMICS_WOW="-"
        ATOMICS_WOW_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
        FASTNAN_WOW_0="FASTNAN_WOW=0"
        FASTNAN_WOW="0"
        FASTNAN_WOW_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
echo "export BOX64_DYNAREC_FASTNAN=0">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
        SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=2"
        SAFEFLAGS_WOW="2"
        SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
        STRONGMEM_WOW_0="STRONGMEM_WOW=1"
        STRONGMEM_WOW="1"
        STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
echo "export BOX64_DYNAREC_STRONGMEM=1">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        WAIT_WOW_0="WAIT_WOW=-"
        WAIT_WOW="-"
        WAIT_WOW_64="echo 'unset BOX64_DYNAREC_WAIT'"
echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
        X87DOUBLE_WOW_0="X87DOUBLE_WOW=1"
        X87DOUBLE_WOW="1"
        X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
        CALLRET_WOW_0="CALLRET_WOW=0"
        CALLRET_WOW="0"
        CALLRET_WOW_64="echo 'echo BOX64_DYNAREC_CALLRET=0'"
echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
        FASTROUND_WOW_0="FASTROUND_WOW=-"
        FASTROUND_WOW="-"
        FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynare
        IGNOREINT3_WOW_0="IGNOREINT3_WOW=-"
        IGNOREINT3_WOW="-"
        IGNOREINT3_WOW_64="echo 'unset BOX64_IGNOREINT3'"
echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
    elif [ $FIRST_CHAR = "3" ]; then
        ATOMICS_WOW_0="ATOMICS_WOW=-"
        ATOMICS_WOW="-"
        ATOMICS_WOW_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
        FASTNAN_WOW_0="FASTNAN_WOW=-"
        FASTNAN_WOW="-"
        FASTNAN_WOW_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
echo "unset BOX64_DYNAREC_FASTNAN">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
        SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=-"
        SAFEFLAGS_WOW="-"
        SAFEFLAGS_WOW_64="echo 'unset BOX64_DYNAREC_SAFEFLAGS'"
echo "unset BOX64_DYNAREC_SAFEFLAGS">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
        STRONGMEM_WOW_0="STRONGMEM_WOW=-"
        STRONGMEM_WOW="-"
        STRONGMEM_WOW_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
echo "unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        WAIT_WOW_0="WAIT_WOW=-"
        WAIT_WOW="-"
        WAIT_WOW_64="echo 'unset BOX64_DYNAREC_WAIT'"
echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
        X87DOUBLE_WOW_0="X87DOUBLE_WOW=-"
        X87DOUBLE_WOW="-"
        X87DOUBLE_WOW_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
echo "unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
        CALLRET_WOW_0="CALLRET_WOW=0"
        CALLRET_WOW="0"
        CALLRET_WOW_64="echo 'echo BOX64_DYNAREC_CALLRET=0'"
echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
        FASTROUND_WOW_0="FASTROUND_WOW=-"
        FASTROUND_WOW="-"
        FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynare
        IGNOREINT3_WOW_0="IGNOREINT3_WOW=-"
        IGNOREINT3_WOW="-"
        IGNOREINT3_WOW_64="echo 'unset BOX64_IGNOREINT3'"
echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
    elif [ $FIRST_CHAR = "4" ]; then
        ATOMICS_WOW_0="ATOMICS_WOW=-"
        ATOMICS_WOW="-"
        ATOMICS_WOW_64="echo 'unset BOX64_DYNAREC_ALIGNED_ATOMICS'"
echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
        FASTNAN_WOW_0="FASTNAN_WOW=-"
        FASTNAN_WOW="-"
        FASTNAN_WOW_64="echo 'unset BOX64_DYNAREC_FASTNAN'"
echo "unset BOX64_DYNAREC_FASTNAN">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
        SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=0"
        SAFEFLAGS_WOW="0"
        SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=0'"
echo "export BOX64_DYNAREC_SAFEFLAGS=0">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
        STRONGMEM_WOW_0="STRONGMEM_WOW=-"
        STRONGMEM_WOW="-"
        STRONGMEM_WOW_64="echo 'unset BOX64_DYNAREC_STRONGMEM'"
echo "unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        WAIT_WOW_0="WAIT=-"
        WAIT_WOW="-"
        WAIT_WOW_64="echo 'unset BOX64_DYNAREC_WAIT'"
echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
        X87DOUBLE_WOW_0="X87DOUBLE_WOW=-"
        X87DOUBLE_WOW="-"
        X87DOUBLE_WOW_64="echo 'unset BOX64_DYNAREC_X87DOUBLE'"
echo "unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
        CALLRET_WOW_0="CALLRET_WOW=0"
        CALLRET_WOW="0"
        CALLRET_WOW_64="echo 'echo BOX64_DYNAREC_CALLRET=0'"
echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
        FASTROUND_WOW_0="FASTROUND_WOW=-"
        FASTROUND_WOW="-"
        FASTROUND_WOW_64="echo 'unset BOX64_DYNAREC_FASTROUND'"
echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynare
        IGNOREINT3_WOW_0="IGNOREINT3_WOW=-"
        IGNOREINT3_WOW="-"
        IGNOREINT3_WOW_64="echo 'unset BOX64_IGNOREINT3'"
echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
        fi
for (( j=1; j<${#DYNAREC_CHOICE}; j++ )); do
    case ${DYNAREC_CHOICE:$j:1} in
        1)
        	FASTNAN_WOW_0="FASTNAN_WOW=0"
            FASTNAN_WOW="0"
            FASTNAN_WOW_64="echo 'export BOX64_DYNAREC_FASTNAN=0'"
echo "export BOX64_DYNAREC_FASTNAN=0">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
        ;;
        2)
        	X87DOUBLE_WOW_0="X87DOUBLE_WOW=1"
            X87DOUBLE_WOW="1"
            X87DOUBLE_WOW_64="echo 'export BOX64_DYNAREC_X87DOUBLE=1'"
echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
        ;;
        3)
            STRONGMEM_WOW_0="STRONGMEM_WOW=1"
            STRONGMEM_WOW="1"
            STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=1'"
echo "export BOX64_DYNAREC_STRONGMEM=1">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        ;;
        4)
            SAFEFLAGS_WOW_0="SAFEFLAGS_WOW=2"
            SAFEFLAGS_WOW="2"
            SAFEFLAGS_WOW_64="echo 'export BOX64_DYNAREC_SAFEFLAGS=2'"
echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
        ;;
        5)
            CALLRET_WOW_0="CALLRET_WOW=1"
            CALLRET_WOW="1"
            CALLRET_WOW_64="echo 'echo BOX64_DYNAREC_CALLRET=1'"
echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
        ;;
        6) 
            FASTROUND_WOW_0="FASTROUND_WOW=0"
            FASTROUND_WOW="0"
            FASTROUND_WOW_64="echo 'export BOX64_DYNAREC_FASTROUND=0'"
echo "export BOX64_DYNAREC_FASTROUND=0">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
        ;;
        7) 
            STRONGMEM_WOW_0="STRONGMEM_WOW=3"
            STRONGMEM_WOW="3"
            STRONGMEM_WOW_64="echo 'export BOX64_DYNAREC_STRONGMEM=3'"
echo "export BOX64_DYNAREC_STRONGMEM=3">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
        ;;
        8) 
            BIGBLOCK_WOW_0="BIGBLOCK_WOW=0"
            BIGBLOCK_WOW="0"
            BIGBLOCK_WOW_64_64="echo 'export BOX64_DYNAREC_BIGBLOCK=0'"
echo "export BOX64_DYNAREC_BIGBLOCK=0">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
        ;;
        9) 
            IGNOREINT3_WOW_0="IGNOREINT3_WOW=1"
            IGNOREINT3_WOW="1"
            IGNOREINT3_WOW_64="echo 'export BOX64_IGNOREINT3=1'"
echo "export BOX64_IGNOREINT3=1">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
        ;;
        esac
    done
else
    return
fi
BIGBLOCK_WOW="2"
BIGBLOCK_WOW_0="BIGBLOCK_WOW=2"
BIGBLOCK_WOW_64="echo 'export BOX64_DYNAREC_BIGBLOCK=2'"
echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
sed -i "49s/.*/$ATOMICS_WOW_0/" "$CONFIG"
sed -i "50s/.*/$BIGBLOCK_WOW_0/" "$CONFIG"
sed -i "51s/.*/$FASTNAN_WOW_0/" "$CONFIG"
sed -i "52s/.*/$SAFEFLAGS_WOW_0/" "$CONFIG"
sed -i "53s/.*/$STRONGMEM_WOW_0/" "$CONFIG"
sed -i "54s/.*/$WAIT_WOW_0/" "$CONFIG"
sed -i "55s/.*/$X87DOUBLE_WOW_0/" "$CONFIG"
sed -i "56s/.*/$CALLRET_WOW_0/" "$CONFIG"
sed -i "57s/.*/$FASTROUND_WOW_0/" "$CONFIG"
sed -i "58s/.*/$IGNOREINT3_WOW_0/" "$CONFIG"
sed -i "64s/.*/$ATOMICS_WOW_64/" "$CONFIG"
sed -i "65s/.*/$BIGBLOCK_WOW_64/" "$CONFIG"
sed -i "66s/.*/$FASTNAN_WOW_64/" "$CONFIG"
sed -i "67s/.*/$SAFEFLAGS_WOW_64/" "$CONFIG"
sed -i "68s/.*/$STRONGMEM_WOW_64/" "$CONFIG"
sed -i "69s/.*/$WAIT_WOW_64/" "$CONFIG"
sed -i "70s/.*/$X87DOUBLE_WOW_64/" "$CONFIG"
sed -i "71s/.*/$CALLRET_WOW_64/" "$CONFIG"
sed -i "72s/.*/$FASTROUND_WOW_64/" "$CONFIG"
sed -i "73s/.*/$IGNOREINT3_WOW_64/" "$CONFIG"
save_settings
}
if [[ "$DYNAREC_CHOICE" =~ ^[0-9]+$ ]]; then
    if [ "$DYNAREC_CHOICE" = "5" ]; then
    dialog --no-shadow \
    --msgbox "💡 Информация\n\n
Список основных предустановок:\n
1 - максимальная совместимость (медленная)\n
2 - по умолчанию + совместимость\n
3 - по умолчанию (SAFEFLAGS=1)\n
4 - производительный (SAFEFLAGS=0)\n\n
Список дополнительных предустановок:\n
1 - FASTNAN=0 - оптимизирует проверку NaN\n
2 - X87DOUBLE=1 - улучшает оптимизацию\n
3 - STRONGMEM=1- обработкa памяти\n
4 - SAFEFLAGS=2 - точность эмуляции\n
    процессора (замедляет работу программ)\n
5 - CALLRET=1 -улучшает производительность\n
6 - FASTROUND=1 - ускоряет работу игры\n
7 - STRONGMEM=3 - надежнее работает игра,\n
    но замедляет ее\n
8 - BIGBLOCK=0 - исправляет зависания в\n
    некоторых играх\n
9 - IGNOREINT3=1 - игнорировать этот флаг\n\n
Например: 12345\n
1 - основная предустановка\n
2,3,4,5 - дополнительные предустановки" 29 46
    fi
    if [ "$DYNAREC_CHOICE" -gt 0 ] && [ "$DYNAREC_CHOICE" -ne 5 ]; then
        set_dynarec
        break
    elif [ "$DYNAREC_CHOICE" -ne 5 ]; then
        set_dynarec_param
        if [ $ext = "1" ] ; then
DYNAREC_64="$ATOMICS_WOW,$BIGBLOCK_WOW,$FASTNAN_WOW,$SAFEFLAGS_WOW,$STRONGMEM_WOW,$WAIT_WOW,$X87DOUBLE_WOW,$CALLRET_WOW,$FASTROUND_WOW,$IGNOREINT3_WOW"
sed -i "47s/.*/DYNAREC_64=$DYNAREC_64/" "$CONFIG"
sed -i "48s/.*/d=0/" "$CONFIG"
sed -i "49s/.*/$ATOMICS_WOW_0/" "$CONFIG"
sed -i "50s/.*/$BIGBLOCK_WOW_0/" "$CONFIG"
sed -i "51s/.*/$FASTNAN_WOW_0/" "$CONFIG"
sed -i "52s/.*/$SAFEFLAGS_WOW_0/" "$CONFIG"
sed -i "53s/.*/$STRONGMEM_WOW_0/" "$CONFIG"
sed -i "54s/.*/$WAIT_WOW_0/" "$CONFIG"
sed -i "55s/.*/$X87DOUBLE_WOW_0/" "$CONFIG"
sed -i "56s/.*/$CALLRET_WOW_0/" "$CONFIG"
sed -i "57s/.*/$FASTROUND_WOW_0/" "$CONFIG"
sed -i "58s/.*/$IGNOREINT3_WOW_0/" "$CONFIG"
sed -i "64s/.*/$ATOMICS_WOW_64/" "$CONFIG"
sed -i "65s/.*/$BIGBLOCK_WOW_64/" "$CONFIG"
sed -i "66s/.*/$FASTNAN_WOW_64/" "$CONFIG"
sed -i "67s/.*/$SAFEFLAGS_WOW_64/" "$CONFIG"
sed -i "68s/.*/$STRONGMEM_WOW_64/" "$CONFIG"
sed -i "69s/.*/$WAIT_WOW_64/" "$CONFIG"
sed -i "70s/.*/$X87DOUBLE_WOW_64/" "$CONFIG"
sed -i "71s/.*/$CALLRET_WOW_64/" "$CONFIG"
sed -i "72s/.*/$FASTROUND_WOW_64/" "$CONFIG"
sed -i "73s/.*/$IGNOREINT3_WOW_64/" "$CONFIG"
            save_settings
        return
        fi
    fi
fi
done