#!/bin/bash

castom_hud() {
LAST_SERVICES_86=${LAST_SERVICES_86:-1}
while true; do
    SCALE_OPACITY_86=$(dialog --no-shadow \
    --title "Кастомная комбинация HUD" \
    --default-item "$LAST_SERVICES_86" \
    --menu "\n
  Выберите комбинацию параметров, которые\n
будут отображаться на экране, для получения\n
        необходимой вам информации" \
    16 47 6 \
    "DXVK v1.10.03-async" "$chek_ver_86   VERSION" \
    "D3D11 FL11_0" "$chek_api_86   API" \
    "FPS: 999.9" "$chek_fps_86   FPS" \
    "Driver: 24.0.99" "$chek_info_86   DEVINFO" \
    "|||||||||||||||||||" "$chek_fram_86   FRAMETIMES" \
    "GPU: 50%" "$chek_gpu_86   GPULOAD" 2>&1 >/dev/tty)
    case $? in
        1) 
        if [[ $chek_ver_86 == "🔲" ]]; then
                vers_86=""
                vers_hos=""
        else
                vers_86="version"
                vers_hos="DXVK v1.10.03-async"
        fi
            if [[ $chek_fps_86 == "🔲" ]]; then
                fps_86=""
                fps_hos=""
        else
                fps_86="fps"
                fps_hos="FPS: 999.9"
            fi
            if [[ $chek_api_86 == "🔲" ]]; then
                api_86=""
                api_hos=""
        else
                api_86="api"
                api_hos="D3D11 FL11_0"
            fi
            if [[ $chek_info_86 == "🔲" ]]; then
                info_86=""
                info_hos=""
        else
                info_86="devinfo"
                info_hos="Turnip Adreno (TM) 640\nDriver: 24.0.99\nVulcan: 1.3.278"
            fi
            if [[ $chek_fram_86 == "🔲" ]]; then
                fram_86=""
                fram_hos=""
        else
                fram_86="frametimes"
                fram_hos="|||||||||||||||||||"
            fi
            if [[ $chek_gpu_86 == "🔲" ]]; then
                gpu_86=""
                gpu_hos=""
        else
                gpu_86="gpuload"
                gpu_hos="GPU: 50%"
            fi
            HUD_86=""
[[ -n "$vers_hos" ]] && HUD_86+="$vers_hos\n"
[[ -n "$api_hos" ]] && HUD_86+="$api_hos\n"
[[ -n "$fps_hos" ]] && HUD_86+="$fps_hos\n"
[[ -n "$info_hos" ]] && HUD_86+="$info_hos\n"
[[ -n "$fram_hos" ]] && HUD_86+="$fram_hos\n"
[[ -n "$gpu_hos" ]] && HUD_86+="$gpu_hos"
HUD_86=${HUD_86%"\n"} 
HUD="$vers_86,$fps_86,$api_86,$info_86,$fram_86,$gpu_86,"
HUD=$(echo "$HUD" | sed 's/,\+/,/g')
HUD=$(echo "$HUD" | sed 's/^,//')
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
h_hud=$(echo -e "$HUD_86" | grep -c '^')
X_86=$((22 + h_hud))
sed -i '97s|.*|vers_86="'"$vers_86"'" api_86="'"$api_86"'" fps_86="'"$fps_86"'" info_86="'"$info_86"'" fram_86="'"$fram_86"'" gpu_86="'"$gpu_86"'" SCALE_86="'"$SCALE_86"'" full_86="'"$full_86"'"|' "$CONFIG"
GALLIUM_CLASS="simple,fps"
if [[ $HUD_86 == "" ]]; then
HUD_86="
          HUD не отображается"
          GALLIUM_CLASS="NO HUD"
    sd_86=0
    X_86=21
fi

        break ;;
    esac
    LAST_SERVICES_86=$SCALE_OPACITY_86
    case $SCALE_OPACITY_86 in
        "DXVK v1.10.03-async")
            if [[ $chek_ver_86 == "✅" ]]; then
                chek_ver_86="🔲"
            else
                chek_ver_86="✅"
            fi
            ;;
        "D3D11 FL11_0")
            if [[ $chek_api_86 == "✅" ]]; then
                chek_api_86="🔲"
            else
                chek_api_86="✅"
            fi
            ;;
        "FPS: 999.9")
            if [[ $chek_fps_86 == "✅" ]]; then
                chek_fps_86="🔲"
            else
                chek_fps_86="✅"
            fi
            ;;
        "Driver: 24.0.99")
            if [[ $chek_info_86 == "✅" ]]; then
                chek_info_86="🔲"
            else
                chek_info_86="✅"
            fi
            ;;
        "|||||||||||||||||||")
            if [[ $chek_fram_86 == "✅" ]]; then
                chek_fram_86="🔲"
            else
                chek_fram_86="✅"
            fi
            ;;
        "GPU: 50%")
            if [[ $chek_gpu_86 == "✅" ]]; then
                chek_gpu_86="🔲"
            else
                chek_gpu_86="✅"
            fi
            ;;
        esac
done
}
LAST_HUD_86=${LAST_HUD_86:-1}
while true; do
            if [ "$HD_86" == 0 ]; then
            HUD_86="
          HUD не отображается"
            elif [ "$HD_86" == 1 ]; then
            HUD_86="DXVK v1.10.03-async \n
FPS: 999.9"
			elif [ "$HD_86" == 2 ]; then
            HUD_86="FPS: 999.9 \n
GPU: 50%"
			elif [ "$HD_86" == 3 ]; then
            HUD_86="FPS: 999.9 \n
||||||||||||||||||| \n
GPU: 50%"
            elif [ "$HD_86" == 4 ]; then
            HUD_86="DXVK v1.10.03-async \n
D3D11 FL11_0 \n
FPS: 999.9 \n
GPU: 50%"
			elif [ "$HD_86" == 5 ]; then
            HUD_86="DXVK v1.10.03-async \n
FPS: 999.9 \n
||||||||||||||||||| \n
GPU: 50%"
            elif [ "$HD_86" == 6 ]; then
            HUD_86="DXVK v1.10.03-async \n
D3D11 FL11_0 \n
FPS: 999.9 \n
Turnip Adreno (TM) 640 \n
Driver: 24.0.99 \n
Vulcan: 1.3.278 \n
||||||||||||||||||| \n
GPU: 50%"
            elif [ "$HD_86" == 7 ]; then
HUD_86=$HUD_86
            elif [ "$HD_86" == 8 ]; then
            HUD_86="
Выбрана комбинация, состоящая из полного\n 
   списка параметров HUD (для тестов)"
            fi
			if [ "$sd_86" == 0 ]; then
GAME_CHOICE_86=$(dialog --no-shadow \
--title "Настройки HUD" --default-item "$LAST_HUD_86" --menu "
   Выберите необходимые параметры для\n
 отображения их на экране (не работает с\n
           драйверами wined3d) \n
────────────────────────────────────────── \n
$HUD_86 \n
────────────────────────────────────────── \n
" "$X_86" 46 9 \
                "1" "$HUD_CHEK_1_86 Отключить HUD" \
                "2" "$HUD_CHEK_2_86 DXVK и FPS" \
                "3" "$HUD_CHEK_3_86 FPS и GPU" \
                "4" "$HUD_CHEK_4_86 FPS,FrameTimes,GPU" \
                "5" "$HUD_CHEK_5_86 DXVK,d3d,FPS,GPU" \
                "6" "$HUD_CHEK_6_86 DXVK,FPS,FrameTimes,GPU" \
                "7" "$HUD_CHEK_7_86 DXVK,d3d,FPS,DevInfo,Frame,GPU" \
                "8" "$HUD_CHEK_8_86 Своя комбинация параметров" \
                "9" "$HUD_CHEK_9_86 Весь список переменных" 2>&1 >/dev/tty)
			elif [ "$sd_86" == 1 ]; then
GAME_CHOICE_86=$(dialog --no-shadow \
--title "Настройки HUD" --default-item "$LAST_HUD_86" --menu "
Необходимые параметры для отображения их\n
   на экране (не работает с драйверами\n
                 wined3d) \n
────────────────────────────────────────── \n
$HUD_86 \n
────────────────────────────────────────── \n
Масштаб:      $SC_86%" "$X_86" 46 10 \
                "1" "$HUD_CHEK_1_86 Отключить HUD" \
                "2" "$HUD_CHEK_2_86 DXVK и FPS" \
                "3" "$HUD_CHEK_3_86 FPS и GPU" \
                "4" "$HUD_CHEK_4_86 FPS,FrameTimes,GPU" \
                "5" "$HUD_CHEK_5_86 DXVK,d3d,FPS,GPU" \
                "6" "$HUD_CHEK_6_86 DXVK,FPS,FrameTimes,GPU" \
                "7" "$HUD_CHEK_7_86 DXVK,d3d,FPS,DevInfo,Frame,GPU" \
                "8" "$HUD_CHEK_8_86 Своя комбинация параметров" \
                "9" "$HUD_CHEK_9_86 Весь список переменных" \
                "10" "   Масштаб HUD-счетчика" 2>&1 >/dev/tty)
			fi
            case $? in
                1) break ;;
                255) continue ;;
            esac
			LAST_HUD_86=$GAME_CHOICE_86
            case $GAME_CHOICE_86 in
            1) 
HUD_CHEK_1_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=0
            X_86=21
            sd_86=0
GALLIUM_HUD_86="unset GALLIUM_HUD"
DXVK_HUD_86="unset DXVK_HUD"
HUD_CLASS="NO HUD"
GALLIUM_CLASS="NO HUD"
vers_86=""
api_86=""
fps_86=""
info_86=""
fram_86=""
gpu_86=""
full_86=""
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            2)
HUD_CHEK_2_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_1_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=1
            X_86=24
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86="version"
api_86=""
fps_86="fps"
info_86=""
fram_86=""
gpu_86=""
HUD="version,fps,"
GALLIUM_CLASS="simple,fps"
full_86=""
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            3)
HUD_CHEK_3_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_1_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=2
            X_86=24
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86=""
api_86=""
fps_86="fps"
info_86=""
fram_86=""
gpu_86="gpuload"
HUD="fps,gpuload,"
GALLIUM_CLASS="simple,fps"
full_86=""
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            4)
HUD_CHEK_4_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_1_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=3
            X_86=25
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86=""
api_86=""
fps_86="fps"
info_86=""
fram_86="frametimes"
gpu_86="gpuload"
HUD="fps,frametimes,gpuload,"
GALLIUM_CLASS="simple,fps"
full_86=""
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            5)
HUD_CHEK_5_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_1_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=4
            X_86=26
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86="version"
api_86="api"
fps_86="fps"
info_86=""
fram_86=""
gpu_86="gpuload"
HUD="version,api,fps,gpuload,"
GALLIUM_CLASS="simple,fps"
full_86=""
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            6)
HUD_CHEK_6_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_1_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=5
            X_86=26
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86="version"
api_86=""
fps_86="fps"
info_86=""
fram_86="frametimes"
gpu_86="gpuload"
HUD="version,fps,frametimes,gpuload,"
GALLIUM_CLASS="simple,fps"
full_86=""
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            7)
HUD_CHEK_7_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_1_86 HUD_CHEK_8_86 HUD_CHEK_9_86)"
            HD_86=6
            X_86=30
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86="version"
api_86="api"
fps_86="fps"
info_86="devinfo"
fram_86="frametimes"
gpu_86="gpuload"
HUD="version,api,fps,devinfo,frametimes,gpuload,"
full_86=""
GALLIUM_CLASS="simple,fps"
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            8)
HUD_CHEK_8_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_1_86 HUD_CHEK_9_86)"
            HD_86=7
            sd_86=1
full_86=""
castom_hud
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            9)
HUD_CHEK_9_86="✅"; eval "$(printf '%s="🔲" ' HUD_CHEK_2_86 HUD_CHEK_3_86 HUD_CHEK_4_86 HUD_CHEK_5_86 HUD_CHEK_6_86 HUD_CHEK_7_86 HUD_CHEK_8_86 HUD_CHEK_1_86)"
            HD_86=8
            X_86=24
            sd_86=1
GALLIUM_HUD_86="export GALLIUM_HUD=simple,fps"
vers_86=""
api_86=""
fps_86=""
info_86=""
fram_86=""
gpu_86=""
HUD="full,"
full_86="full"
GALLIUM_CLASS="simple,fps"
SC="scale=$SCALE_86"
sed -i "122s/.*/HUD_CLASS=\"${HUD}\"/" "$CONFIG"
            ;;
            10) 
SCALE_OPACITY_86=$(dialog --no-shadow \
--title "Масштаб HUD" --menu "\n
Стандартным изначально считается значение 70% \n \n
Выберите масштаб HUD подходящий для разрешения экрана приложения $result " 24 38 11 \
    "1" "$a_86 40%" \
    "2" "$b_86 50%" \
    "3" "$c_86 60%" \
    "4" "$d_86 70%" \
    "5" "$f_86 80%" \
    "6" "$g_86 90%" \
    "7" "$h_86 100%" \
    "8" "$i_86 120%" \
    "9" "$k_86 140%" \
    "10" "$l_86 160%" \
    "11" "$m_86 180%" 2>&1 >/dev/tty)
case $? in
    1) break ;;
    255) 
;;
esac
case $SCALE_OPACITY_86 in
    1) SCALE_86=0.4; SC_86=40; a_86="✅"; eval "$(printf '%s="🔲" ' b_86 c_86 d_86 f_86 g_86 h_86 i_86 k_86 l_86 m_86)"
     ;;
    2) SCALE_86=0.5; SC_86=50; b_86="✅"; eval "$(printf '%s="🔲" ' a_86 c_86 d_86 f_86 g_86 h_86 i_86 k_86 l_86 m_86)"
    ;;
    3) SCALE_86=0.6; SC_86=60; c_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 d_86 f_86 g_86 h_86 i_86 k_86 l_86 m_86)"
    ;;
    4) SCALE_86=0.7; SC_86=70; d_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 f_86 g_86 h_86 i_86 k_86 l_86 m_86)"
    ;;
    5) SCALE_86=0.8; SC_86=80; f_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 g_86 h_86 i_86 k_86 l_86 m_86)"
    ;;
    6) SCALE_86=0.9; SC_86=90; g_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 h_86 i_86 k_86 l_86 m_86)"
    ;;
    7) SCALE_86=1.0; SC_86=100; h_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 g_86 i_86 k_86 l_86 m_86)"
    ;;
    8) SCALE_86=1.2; SC_86=120; i_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 g_86 h_86 k_86 l_86 m_86)"
    ;;
    9) SCALE_86=1.4; SC_86=140; k_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 g_86 h_86 i_86 l_86 m_86)"
    ;;
    10) SCALE_86=1.6; SC_86=160; l_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 g_86 h_86 i_86 k_86 m_86)"
    ;;
    11) SCALE_86=1.8; SC_86=180; m_86="✅"; eval "$(printf '%s="🔲" ' a_86 b_86 c_86 d_86 f_86 g_86 h_86 i_86 k_86 l_86)"
    ;;
esac
SC="scale=$SCALE_86"
sed -i "169s/.*/a_86=$a_86 b_86=$b_86 c_86=$c_86 d_86=$d_86 f_86=$f_86 g_86=$g_86 h_86=$h_86 i_86=$i_86 k_86=$k_86 l_86=$l_86 m_86=$m_86/" "$CONFIG"
sed -i "98s/.*/SC_86=${SC_86}/" "$CONFIG"
esac
sed -i '97s|.*|vers_86="'"$vers_86"'" api_86="'"$api_86"'" fps_86="'"$fps_86"'" info_86="'"$info_86"'" fram_86="'"$fram_86"'" gpu_86="'"$gpu_86"'" SCALE_86="'"$SCALE_86"'" full_86="'"$full_86"'"|' "$CONFIG"
DXVK_HUD_86="export DXVK_HUD=$vers_86,$api_86,$fps_86,$info_86,$fram_86,$gpu_86,$full_86,scale=$SCALE_86"

GALLIUM_HUD_PERIOD_86="export GALLIUM_HUD_PERIOD=1"
echo "$GALLIUM_HUD_86
$GALLIUM_HUD_PERIOD_86
$DXVK_HUD_86">$PREFIX/glibc/opt/conf/hud.conf
sed -i "94s/.*/HD_86=${HD_86}/" "$CONFIG"
sed -i "95s/.*/sd_86=${sd_86}/" "$CONFIG"
sed -i "96s/.*/X_86=${X_86}/" "$CONFIG"
sed -i "162s/.*/chek_ver_86=\"${chek_ver_86}\"/" "$CONFIG"
sed -i "163s/.*/chek_fps_86=\"${chek_fps_86}\"/" "$CONFIG"
sed -i "164s/.*/chek_api_86=\"${chek_api_86}\"/" "$CONFIG"
sed -i "165s/.*/chek_info_86=\"${chek_info_86}\"/" "$CONFIG"
sed -i "166s/.*/chek_fram_86=\"${chek_fram_86}\"/" "$CONFIG"
sed -i "167s/.*/chek_gpu_86=\"${chek_gpu_86}\"/" "$CONFIG"
sed -i "168s/.*/HUD_86=\"$(echo -e "$HUD_86" | sed ':a;N;$!ba;s/\n/\\\\n/g' | sed 's/"/\\"/g')\"/" "$CONFIG"
sed -i "174s/.*/HUD_CHEK_1_86=$HUD_CHEK_1_86 HUD_CHEK_2_86=$HUD_CHEK_2_86 HUD_CHEK_3_86=$HUD_CHEK_3_86 HUD_CHEK_4_86=$HUD_CHEK_4_86 HUD_CHEK_5_86=$HUD_CHEK_5_86 HUD_CHEK_6_86=$HUD_CHEK_6_86 HUD_CHEK_7_86=$HUD_CHEK_7_86 HUD_CHEK_8_86=$HUD_CHEK_8_86 HUD_CHEK_9_86=$HUD_CHEK_9_86/" "$CONFIG"
sed -i "123s|.*|$SC|" "$CONFIG"
sed -i "94s/.*/HD_86=${HD_86}/" "$CONFIG"
sed -i "176s/.*/GALLIUM_HUD_86=\"$GALLIUM_CLASS\"/" "$CONFIG"
sed -i "177s/.*/GALLIUM_HUD_PERIOD_86=\"$GALLIUM_HUD_PERIOD_86\"/" "$CONFIG"
sed -i "178s/.*/DXVK_HUD_86=\"$DXVK_HUD_86\"/" "$CONFIG"
done
