#!/bin/bash

defitem=1

while true; do
dialog_menu_item $defitem "Резервное копирование и восстановление" "" \
"1" "Восстановить настройки по умолчанию" \
"2" "Удалить"
defitem=$?
case $defitem in
1)
	dialog_yesno "Вы уверены?"
	if [ "$?" = "0" ]; then
		rm -rf $PREFIX/glibc/opt/conf
		cp -r $PREFIX/glibc/opt/default-conf/* $PREFIX/glibc/opt
	fi
;;
2)
	dialog_yesno "Вы уверены?"
	if [ "$?" = "0" ]; then
		restore-termux-style
		tput cnorm
		rm -rf $PREFIX/glibc
		rm -rf $PREFIX/bin/mobox
		exit
	fi
;;
255)
	break
;;
esac

done
