#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Root settings" "" \
	"1" "Закрыть фоновые приложения" \
	"2" "OOM Настройщик (предотвратить закрытие termux)" \
	"3" "Увеличьте количество виртуальных машин." \
	"4" "Отключить закрытие фантомных процессов"
defitem=$?
case $defitem in
1)
	chmod 777 $PREFIX/glibc/opt/scripts/close-apps
	sudo bash $PREFIX/glibc/opt/scripts/close-apps
	sleep 3
;;
2)
	chmod 777 $PREFIX/glibc/opt/scripts/termux-adj
	sudo bash $PREFIX/glibc/opt/scripts/termux-adj &
	echo "Теперь запущен OOM регулятор. Пожалуйста, не используйте эту опцию более одного раза! Чтобы остановить ее - принудительно, остановите Termux"
	sleep 4
;;
3)
	su -c "echo 2147483642 > /proc/sys/vm/max_map_count"
;;
4)
	su -c "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"
;;
255)
	break
;;
esac
done
