#!/bin/bash

defitem=1

while true; do
if [ ! -e $PREFIX/glibc/opt/virgl/virgl-enabled ]; then
	virgl_state="not "
fi
load_configs
dialog_menu_item $defitem "Настройки VirGL" "\ZbТекущие настройки:\Zn
	\Z3MESA_GL_VERSION_OVERRIDE\Z2=\Zn$MESA_GL_VERSION_OVERRIDE
	\Z3MESA_GLSL_VERSION_OVERRIDE\Z2=\Zn$MESA_GLSL_VERSION_OVERRIDE
	\Z3MESA_EXTENSION_OVERRIDE\Z2=\Zn$MESA_EXTENSION_OVERRIDE

	\Z7VirGL is ${virgl_state}Установлен\Zn" \
"1" "GL 2.1" \
"2" "GL 2.1, dxTn (по умолчанию)" \
"3" "GL 3.3" \
"4" "GL 3.3, dxTN"
defitem=$?
case $defitem in
1)
cp $PREFIX/glibc/opt/virgl/virgl21nodxtn.conf $PREFIX/glibc/opt/conf/virgl.conf
;;
2)
cp $PREFIX/glibc/opt/virgl/virgl21.conf $PREFIX/glibc/opt/conf/virgl.conf
;;
3)
cp $PREFIX/glibc/opt/virgl/virgl33nodxtn.conf $PREFIX/glibc/opt/conf/virgl.conf
;;
4)
cp $PREFIX/glibc/opt/virgl/virgl33.conf $PREFIX/glibc/opt/conf/virgl.conf
;;
255)
break
;;
esac
done
